# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
a =np.array([[12,12,12],[21,21,21],[20,21,22]])
print(a)

[[12 12 12]
 [21 21 21]
 [20 21 22]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [43]:
import numpy as np
b=np.zeros([5,5])
print(b)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
b[1][0]=1
b[2][1]=2
b[3][2]=3
b[4][3]=4
print(b)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [14]:
import numpy as np
a=np.zeros([8,8])
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [16]:
import numpy as np
a=np.random.random([5,5])
print(a)

[[0.82493486 0.67758441 0.43660745 0.63315073 0.42854799]
 [0.26818656 0.30583527 0.20280754 0.47093153 0.37047057]
 [0.7454392  0.53340447 0.46205537 0.35674587 0.33118606]
 [0.17063582 0.87577199 0.25191406 0.47692396 0.38337437]
 [0.66139897 0.22753493 0.82897029 0.47637324 0.20375879]]


In [45]:
bmax=b.max()
bmin=b.min()
b=(b-bmin)/(bmax-bmin)
print("normalisation done:-")
print(b)


normalisation done:-
[[0.   0.   0.   0.   0.  ]
 [0.25 0.   0.   0.   0.  ]
 [0.   0.5  0.   0.   0.  ]
 [0.   0.   0.75 0.   0.  ]
 [0.   0.   0.   1.   0.  ]]


# 5.  How to find common values between two arrays?

In [4]:
import numpy as np
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[10,100,20],[40,400,50]])
print(arr1)
print(arr2)

[[10 20 30]
 [40 50 60]]
[[ 10 100  20]
 [ 40 400  50]]


In [7]:
print(np.intersect1d(arr1,arr2))

[10 20 40 50]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-07-30
2020-07-31
2020-08-01


# 7. Consider two random array A and B, check if they are equal

In [9]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [21]:
import numpy as np
Z = np.random.random(10)

Z[Z.argmax()] = 0
print(Z)


[0.39778517 0.54303297 0.02227582 0.40674231 0.7522988  0.77602424
 0.39024575 0.         0.53950991 0.26705207]


# 9. How to print all the values of an array?

In [23]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [26]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[9 5 9 7 2 2 8 1 4 8 6 0 1 1 3 1 1 5 2 9 6 0 9 6 0 6 7 8 8 7 9 1 5 5 6 2 9
 7 2 0 8 9 3 1 5 5 5 3 5 2]
5


# 14.How to get the n largest values of an array

# 15.How to create a record array from a regular array?